// <auto-generated />
namespace Home.Migrations.IdentityFolder
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Secondmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Secondmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201506092212544_Secondmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
